apiVersion: apps/v1
kind: Deployment
metadata:
  name: wind-data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wind-data-app
  template:
    metadata:
      labels:
        app: wind-data-app
    spec:
      containers:
      - name: wind-data-container
        image: dlrimage
        volumeMounts:
        - name: dlrts-cert
          mountPath: /etc/ssl/certs/dlrts.pem
          subPath: dlrts.pem
        - name: dlrts-key
          mountPath: /etc/ssl/certs/dlrts.key
          subPath: dlrts.key
      volumes:
      - name: dlrts-cert
        secret:
          secretName: dlrts-cert
      - name: dlrts-key
        secret:
          secretName: dlrts-key
